version: "3.9"
services:
  db:
    container_name: case-app-db
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=service
      - POSTGRES_USER=service
      - POSTGRES_DB=service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U service" ]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "6543:5432"

  migrate:
    container_name: case-app-db-migrate
    image: "migrate/migrate:v4.15.2"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://service:service@case-app-db:5432/service?sslmode=disable",
        "up"
      ]
